# -*- encoding : utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Pokemonlist.create(:name => "フシギダネ", :no => 1, :typea => "くさ", :typeb => "どく")
Pokemonlist.create(:name => "フシギソウ", :no => 2, :typea => "くさ", :typeb => "どく")
Pokemonlist.create(:name => "フシギバナ", :no => 3, :typea => "くさ", :typeb => "どく")
Pokemonlist.create(:name => "ヒトカゲ", :no => 4, :typea => "ほのお")
Pokemonlist.create(:name => "リザード", :no => 5, :typea => "ほのお")
Pokemonlist.create(:name => "リザードン", :no => 6, :typea => "ほのお", :typeb => "ひこう")
Pokemonlist.create(:name => "ゼニガメ", :no => 7, :typea => "みず")
Pokemonlist.create(:name => "カメール", :no => 8, :typea => "みず")
Pokemonlist.create(:name => "カメックス", :no => 9, :typea => "みず")
Pokemonlist.create(:name => "キャタピー", :no => 10, :typea => "むし")
Pokemonlist.create(:name => "トランセル", :no => 11, :typea => "むし")
Pokemonlist.create(:name => "バタフリー", :no => 12, :typea => "むし", :typeb => "ひこう")
Pokemonlist.create(:name => "ビードル", :no => 13, :typea => "むし", :typeb => "どく")
Pokemonlist.create(:name => "コクーン", :no => 14, :typea => "むし", :typeb => "どく")
Pokemonlist.create(:name => "スピアー", :no => 15, :typea => "むし", :typeb => "どく")
Pokemonlist.create(:name => "ポッポ", :no => 16, :typea => "ノーマル", :typeb => "ひこう")
Pokemonlist.create(:name => "ピジョン", :no => 17, :typea => "ノーマル", :typeb => "ひこう")
Pokemonlist.create(:name => "ピジョット", :no => 18, :typea => "ノーマル", :typeb => "ひこう")
Pokemonlist.create(:name => "コラッタ", :no => 19, :typea => "ノーマル")
Pokemonlist.create(:name => "ラッタ", :no => 20, :typea => "ノーマル")
Pokemonlist.create(:name => "オニスズメ", :no => 21, :typea => "ノーマル", :typeb => "ひこう")
Pokemonlist.create(:name => "オニドリル", :no => 22, :typea => "ノーマル", :typeb => "ひこう")
Pokemonlist.create(:name => "アーボ", :no => 23, :typea => "どく")
Pokemonlist.create(:name => "アーボック", :no => 24, :typea => "どく")
Pokemonlist.create(:name => "ピカチュウ", :no => 25, :typea => "でんき")
Pokemonlist.create(:name => "ライチュウ", :no => 26, :typea => "でんき")
Pokemonlist.create(:name => "サンド", :no => 27, :typea => "じめん")
Pokemonlist.create(:name => "サンドパン", :no => 28, :typea => "じめん")
Pokemonlist.create(:name => "ニドラン♀", :no => 29, :typea => "どく")
Pokemonlist.create(:name => "ニドリーナ", :no => 30, :typea => "どく")
Pokemonlist.create(:name => "ニドクイン", :no => 31, :typea => "どく", :typeb => "じめん")
Pokemonlist.create(:name => "ニドラン♂", :no => 32, :typea => "どく")
Pokemonlist.create(:name => "ニドリーノ", :no => 33, :typea => "どく")
Pokemonlist.create(:name => "ニドキング", :no => 34, :typea => "どく", :typeb => "じめん")
Pokemonlist.create(:name => "ピッピ", :no => 35, :typea => "ノーマル")
Pokemonlist.create(:name => "ピクシー", :no => 36, :typea => "ノーマル")
Pokemonlist.create(:name => "ロコン", :no => 37, :typea => "ほのお")
Pokemonlist.create(:name => "キュウコン", :no => 38, :typea => "ほのお")
Pokemonlist.create(:name => "プリン", :no => 39, :typea => "ノーマル")
Pokemonlist.create(:name => "プクリン", :no => 40, :typea => "ノーマル")
Pokemonlist.create(:name => "ズバット", :no => 41, :typea => "どく", :typeb => "ひこう")
Pokemonlist.create(:name => "ゴルバット", :no => 42, :typea => "どく", :typeb => "ひこう")
Pokemonlist.create(:name => "ナゾノクサ", :no => 43, :typea => "くさ", :typeb => "どく")
Pokemonlist.create(:name => "クサイハナ", :no => 44, :typea => "くさ", :typeb => "どく")
Pokemonlist.create(:name => "ラフレシア", :no => 45, :typea => "くさ", :typeb => "どく")
Pokemonlist.create(:name => "パラス", :no => 46, :typea => "むし", :typeb => "くさ")
Pokemonlist.create(:name => "パラセクト", :no => 47, :typea => "むし", :typeb => "くさ")
Pokemonlist.create(:name => "コンパン", :no => 48, :typea => "むし", :typeb => "どく")
Pokemonlist.create(:name => "モルフォン", :no => 49, :typea => "むし", :typeb => "どく")
Pokemonlist.create(:name => "ディグダ", :no => 50, :typea => "じめん")
Pokemonlist.create(:name => "ダグトリオ", :no => 51, :typea => "じめん")
Pokemonlist.create(:name => "ニャース", :no => 52, :typea => "ノーマル")
Pokemonlist.create(:name => "ペルシアン", :no => 53, :typea => "ノーマル")
Pokemonlist.create(:name => "コダック", :no => 54, :typea => "みず")
Pokemonlist.create(:name => "ゴルダック", :no => 55, :typea => "みず")
Pokemonlist.create(:name => "マンキー", :no => 56, :typea => "かくとう")
Pokemonlist.create(:name => "オコリザル", :no => 57, :typea => "かくとう")
Pokemonlist.create(:name => "ガーディ", :no => 58, :typea => "ほのお")
Pokemonlist.create(:name => "ウインディ", :no => 59, :typea => "ほのお")
Pokemonlist.create(:name => "ニョロモ", :no => 60, :typea => "みず")
Pokemonlist.create(:name => "ニョロゾ", :no => 61, :typea => "みず")
Pokemonlist.create(:name => "ニョロボン", :no => 62, :typea => "みず", :typeb =>"かくとう")
Pokemonlist.create(:name => "ケーシィ", :no => 63, :typea => "エスパー")
Pokemonlist.create(:name => "ユンゲラー", :no => 64, :typea => "エスパー")
Pokemonlist.create(:name => "フーディン", :no => 65, :typea => "エスパー")
Pokemonlist.create(:name => "ワンリキー", :no => 66, :typea => "かくとう")
Pokemonlist.create(:name => "ゴーリキー", :no => 67, :typea => "かくとう")
Pokemonlist.create(:name => "カイリキー", :no => 68, :typea => "かくとう")
Pokemonlist.create(:name => "マダツボミ", :no => 69, :typea => "くさ", :typeb =>"どく")
Pokemonlist.create(:name => "ウツドン", :no => 70, :typea => "くさ", :typeb =>"どく")
Pokemonlist.create(:name => "ウツボット", :no => 71, :typea => "くさ", :typeb =>"どく")
Pokemonlist.create(:name => "メノクラゲ", :no => 72, :typea => "みず", :typeb =>"どく")
Pokemonlist.create(:name => "ドククラゲ", :no => 73, :typea => "みず", :typeb =>"どく")
Pokemonlist.create(:name => "イシツブテ", :no => 74, :typea => "いわ", :typeb =>"じめん")
Pokemonlist.create(:name => "ゴローン", :no => 75, :typea => "いわ", :typeb =>"じめん")
Pokemonlist.create(:name => "ゴローニャ", :no => 76, :typea => "いわ", :typeb =>"じめん")
Pokemonlist.create(:name => "ポニータ", :no => 77, :typea => "ほのお")
Pokemonlist.create(:name => "ギャロップ", :no => 78, :typea => "ほのお")
Pokemonlist.create(:name => "ヤドン", :no => 79, :typea => "みず")
Pokemonlist.create(:name => "ヤドラン", :no => 80, :typea => "みず", :typeb =>"エスパー")
Pokemonlist.create(:name => "コイル", :no => 81, :typea => "でんき", :typeb =>"はがね")
Pokemonlist.create(:name => "レアコイル", :no => 82, :typea => "でんき", :typeb =>"はがね")
Pokemonlist.create(:name => "カモネギ", :no => 83, :typea => "ノーマル", :typeb =>"ひこう")
Pokemonlist.create(:name => "ドードー", :no => 84, :typea => "ノーマル", :typeb =>"ひこう")
Pokemonlist.create(:name => "ドードリオ", :no => 85, :typea => "ノーマル",:typeb =>"ひこう")
Pokemonlist.create(:name => "パウワウ", :no => 86, :typea => "みず", :typeb =>"こおり")
Pokemonlist.create(:name => "ジュゴン", :no => 87, :typea => "みず", :typeb =>"こおり")
Pokemonlist.create(:name => "ベトベター", :no => 88, :typea => "どく")
Pokemonlist.create(:name => "ベトンベトン", :no => 89, :typea => "どく")
Pokemonlist.create(:name => "シェルダー", :no => 90, :typea => "みず", :typeb =>"こおり")
Pokemonlist.create(:name => "パルシェン", :no => 91, :typea => "みず", :typeb =>"こおり")
Pokemonlist.create(:name => "ゴース", :no => 92, :typea => "ゴースト", :typeb =>"どく")
Pokemonlist.create(:name => "ゴースト", :no => 93, :typea => "ゴースト", :typeb =>"どく")
Pokemonlist.create(:name => "ゲンガー", :no => 94, :typea => "ゴースト", :typeb =>"どく")
Pokemonlist.create(:name => "イワーク", :no => 95, :typea => "いわ", :typeb =>"じめん")
Pokemonlist.create(:name => "スリープ", :no => 96, :typea => "エスパー")
Pokemonlist.create(:name => "スリーパー", :no => 97, :typea => "エスパー")
Pokemonlist.create(:name => "クラブ", :no => 98, :typea => "みず")
Pokemonlist.create(:name => "キングラー", :no => 99, :typea => "みず")
Pokemonlist.create(:name => "ビリリダマ", :no => 100, :typea => "でんき")
Pokemonlist.create(:name => "マルマイン", :no => 101, :typea => "でんき")
Pokemonlist.create(:name => "タマタマ", :no => 102, :typea => "くさ", :typeb => "エスパー")
Pokemonlist.create(:name => "ナッシー", :no => 103, :typea => "くさ", :typeb => "エスパー")
Pokemonlist.create(:name => "カラカラ", :no => 104, :typea => "じめん")
Pokemonlist.create(:name => "ガラガラ", :no => 105, :typea => "じめん")
Pokemonlist.create(:name => "サワムラー", :no => 106, :typea => "かくとう")
Pokemonlist.create(:name => "エビワラー", :no => 107, :typea => "かくとう")
Pokemonlist.create(:name => "ベロリンガ", :no => 108, :typea => "ノーマル")
Pokemonlist.create(:name => "ドガース", :no => 109, :typea => "どく")
Pokemonlist.create(:name => "マタドガス", :no => 110, :typea => "どく")
Pokemonlist.create(:name => "サイホーン", :no => 111, :typea => "じめん", :typeb => "いわ")
Pokemonlist.create(:name => "サイドン", :no => 112, :typea => "じめん", :typeb => "いわ")
Pokemonlist.create(:name => "ラッキー", :no => 113, :typea => "ノーマル")
Pokemonlist.create(:name => "モンジャラ", :no => 114, :typea => "くさ")
Pokemonlist.create(:name => "ガルーラ", :no => 115, :typea => "ノーマル")
Pokemonlist.create(:name => "タッツー", :no => 116, :typea => "みず")
Pokemonlist.create(:name => "シードラ", :no => 117, :typea => "みず")
Pokemonlist.create(:name => "トサキント", :no => 118, :typea => "みず")
Pokemonlist.create(:name => "アズマオウ", :no => 119, :typea => "みず")
Pokemonlist.create(:name => "ヒトデマン", :no => 120, :typea => "みず")
Pokemonlist.create(:name => "スターミー", :no => 121, :typea => "みず", :typeb => "エスパー")
Pokemonlist.create(:name => "バリヤード", :no => 122, :typea => "エスパー")
Pokemonlist.create(:name => "ストライク", :no => 123, :typea => "むし")
Pokemonlist.create(:name => "ルージェラ", :no => 124, :typea => "こおり", :typeb => "エスパー")
Pokemonlist.create(:name => "エレブー", :no => 125, :typea => "でんき")
Pokemonlist.create(:name => "ブーバー", :no => 126, :typea => "ほのお")
Pokemonlist.create(:name => "カイロス", :no => 127, :typea => "むし")
Pokemonlist.create(:name => "ケンタロス", :no => 128, :typea => "ノーマル")
Pokemonlist.create(:name => "コイキング", :no => 129, :typea => "みず")
Pokemonlist.create(:name => "ギャラドス", :no => 130, :typea => "みず", :typeb => "ひこう")
Pokemonlist.create(:name => "ラプラス", :no => 131, :typea => "みず", :typeb => "こおり")
Pokemonlist.create(:name => "メタモン", :no => 132, :typea => "ノーマル")
Pokemonlist.create(:name => "イーブイ", :no => 133, :typea => "ノーマル")
Pokemonlist.create(:name => "シャワーズ", :no => 134, :typea => "みず")
Pokemonlist.create(:name => "サンダース", :no => 135, :typea => "でんき")
Pokemonlist.create(:name => "ブースター", :no => 136, :typea => "ほのお")
Pokemonlist.create(:name => "ポリゴン", :no => 137, :typea => "ノーマル")
Pokemonlist.create(:name => "オムナイト", :no => 138, :typea => "いわ", :typeb => "みず")
Pokemonlist.create(:name => "オムスター", :no => 139, :typea => "いわ", :typeb => "みず")
Pokemonlist.create(:name => "カブト", :no => 140, :typea => "いわ", :typeb => "みず")
Pokemonlist.create(:name => "カブトプス", :no => 141, :typea => "いわ", :typeb => "みず")
Pokemonlist.create(:name => "プテラ", :no => 142, :typea => "いわ", :typeb => "ひこう")
Pokemonlist.create(:name => "カビゴン", :no => 143, :typea => "ノーマル")
Pokemonlist.create(:name => "フリーザー", :no => 144, :typea => "こおり", :typeb => "ひこう")
Pokemonlist.create(:name => "サンダー", :no => 145, :typea => "でんき", :typeb => "ひこう")
Pokemonlist.create(:name => "ファイヤー", :no => 146, :typea => "ほのお", :typeb => "ひこう")
Pokemonlist.create(:name => "ミニリュウ", :no => 147, :typea => "ドラゴン")
Pokemonlist.create(:name => "ハクリュー", :no => 148, :typea => "ドラゴン")
Pokemonlist.create(:name => "カイリュー", :no => 149, :typea => "ドラゴン", :typeb => "ひこう")
Pokemonlist.create(:name => "ミュウツー", :no => 150, :typea => "エスパー")
Pokemonlist.create(:name => "ミュウ", :no => 151, :typea => "エスパー")
Pokemonlist.create(:name => "チコリータ", :no => 152, :typea => "くさ")
Pokemonlist.create(:name => "ベイリーフ", :no => 153, :typea => "くさ")
Pokemonlist.create(:name => "メガニウム", :no => 154, :typea => "くさ")
Pokemonlist.create(:name => "ヒノアラシ", :no => 155, :typea => "ほのお")
Pokemonlist.create(:name => "マグマラシ", :no => 156, :typea => "ほのお")
Pokemonlist.create(:name => "バクフーン", :no => 157, :typea => "ほのお")
Pokemonlist.create(:name => "ワニノコ", :no => 158, :typea => "みず")
Pokemonlist.create(:name => "アリゲイツ", :no => 159, :typea => "みず")
Pokemonlist.create(:name => "オーダイル", :no => 160, :typea => "みず")
Pokemonlist.create(:name => "オタチ", :no => 161, :typea => "ノーマル")
Pokemonlist.create(:name => "オオタチ", :no => 162, :typea => "ノーマル")
Pokemonlist.create(:name => "ホーホー", :no => 163, :typea => "ノーマル", :typeb =>"ひこう")
Pokemonlist.create(:name => "ヨルノズク", :no => 164, :typea => "ノーマル", :typeb =>"ひこう")
Pokemonlist.create(:name => "レディバ", :no => 165, :typea => "むし", :typeb =>"ひこう")
Pokemonlist.create(:name => "レディアン", :no => 166, :typea => "むし", :typeb =>"ひこう")
Pokemonlist.create(:name => "イトマル", :no => 167, :typea => "むし", :typeb =>"どく")
Pokemonlist.create(:name => "アリアドス", :no => 168, :typea => "むし", :typeb =>"どく")
Pokemonlist.create(:name => "クロバット", :no => 169, :typea => "どく", :typeb =>"ひこう")
Pokemonlist.create(:name => "チョンチー", :no => 170, :typea => "みず", :typeb =>"でんき")
Pokemonlist.create(:name => "ランターン", :no => 171, :typea => "みず", :typeb =>"でんき")
Pokemonlist.create(:name => "ピチュー", :no => 172, :typea => "でんき")
Pokemonlist.create(:name => "ピィ", :no => 173, :typea => "ノーマル")
Pokemonlist.create(:name => "ププリン", :no => 174, :typea => "ノーマル")
Pokemonlist.create(:name => "トゲピー", :no => 175, :typea => "ノーマル")
Pokemonlist.create(:name => "トゲチック", :no => 176, :typea => "ノーマル", :typeb =>"ひこう")
Pokemonlist.create(:name => "ネイティ", :no => 177, :typea => "エスパー", :typeb =>"ひこう")
Pokemonlist.create(:name => "ネイティオ", :no => 178, :typea => "エスパー", :typeb =>"ひこう")
Pokemonlist.create(:name => "メリープ", :no => 179, :typea => "でんき")
Pokemonlist.create(:name => "モココ", :no => 180, :typea => "でんき")
Pokemonlist.create(:name => "デンリュウ", :no => 181, :typea => "でんき")
Pokemonlist.create(:name => "キレイハナ", :no => 182, :typea => "くさ")
Pokemonlist.create(:name => "マリル", :no => 183, :typea => "みず")
Pokemonlist.create(:name => "マリルリ", :no => 184, :typea => "みず")
Pokemonlist.create(:name => "ウソッキー", :no => 185, :typea => "いわ")
Pokemonlist.create(:name => "ニョロトノ", :no => 186, :typea => "みず")
Pokemonlist.create(:name => "ハネッコ", :no => 187, :typea => "くさ", :typeb =>"ひこう")
Pokemonlist.create(:name => "ポポッコ", :no => 188, :typea => "くさ", :typeb =>"ひこう")
Pokemonlist.create(:name => "ワタッコ", :no => 189, :typea => "くさ", :typeb =>"ひこう")
Pokemonlist.create(:name => "エイパム", :no => 190, :typea => "ノーマル")
Pokemonlist.create(:name => "ヒマナッツ", :no => 191, :typea => "くさ")
Pokemonlist.create(:name => "キマワリ", :no => 192, :typea => "くさ")
Pokemonlist.create(:name => "ヤンヤンマ", :no => 193, :typea => "むし", :typeb => "ひこう")
Pokemonlist.create(:name => "ウパー", :no => 194, :typea => "みず", :typeb => "じめん")
Pokemonlist.create(:name => "ヌオー", :no => 195, :typea => "みず", :typeb => "じめん")
Pokemonlist.create(:name => "エーフィ", :no => 196, :typea => "エスパー")
Pokemonlist.create(:name => "ブラッキー", :no => 197, :typea => "あく")
Pokemonlist.create(:name => "ヤミカラス", :no => 198, :typea => "あく", :typeb => "ひこう")
Pokemonlist.create(:name => "ヤドキング", :no => 199, :typea => "みず", :typeb => "エスパー")
Pokemonlist.create(:name => "ムウマ", :no => 200, :typea => "ゴースト")
Pokemonlist.create(:name => "アンノーン", :no => 201, :typea => "エスパー")
Pokemonlist.create(:name => "ソーナンス", :no => 202, :typea => "エスパー")
Pokemonlist.create(:name => "キリンリキ", :no => 203, :typea => "ノーマル", :typeb => "エスパー")
Pokemonlist.create(:name => "クヌギダマ", :no => 204, :typea => "むし")
Pokemonlist.create(:name => "フォレトス", :no => 205, :typea => "むし", :typeb => "はがね")
Pokemonlist.create(:name => "ノコッチ", :no => 206, :typea => "ノーマル")
Pokemonlist.create(:name => "グライガー", :no => 207, :typea => "じめん", :typeb => "ひこう")
Pokemonlist.create(:name => "ハガネール", :no => 208, :typea => "いわ", :typeb => "はがね")
Pokemonlist.create(:name => "ブルー", :no => 209, :typea => "ノーマル")
Pokemonlist.create(:name => "グランブル", :no => 210, :typea => "ノーマル")
Pokemonlist.create(:name => "ハリーセン", :no => 211, :typea => "みず", :typeb => "どく")
Pokemonlist.create(:name => "ハッサム", :no => 212, :typea => "むじ", :typeb => "はがね")
Pokemonlist.create(:name => "ツボツボ", :no => 213, :typea => "むし", :typeb => "いわ")
Pokemonlist.create(:name => "ヘラクロス", :no => 214, :typea => "むし", :typeb => "かくとう")
Pokemonlist.create(:name => "ニューラ", :no => 215, :typea => "あく", :typeb => "こおり")
Pokemonlist.create(:name => "ヒメグマ", :no => 216, :typea => "ノーマル")
Pokemonlist.create(:name => "リングマ", :no => 217, :typea => "ノーマル")
Pokemonlist.create(:name => "マグマッグ", :no => 218, :typea => "ほのお", :typeb => "いわ")
Pokemonlist.create(:name => "マグカルゴ", :no => 219, :typea => "ほのお", :typeb => "いわ")
Pokemonlist.create(:name => "ウリムー", :no => 220, :typea => "こおり", :typeb => "じめん")
Pokemonlist.create(:name => "イノムー", :no => 221, :typea => "こおり", :typeb => "じめん")
Pokemonlist.create(:name => "サニーゴ", :no => 222, :typea => "みず", :typeb => "いわ")
Pokemonlist.create(:name => "テッポウオ", :no => 223, :typea => "みず")
Pokemonlist.create(:name => "オクタン", :no => 224, :typea => "みず")
Pokemonlist.create(:name => "デリバード", :no => 225, :typea => "こおり", :typeb => "ひこう")
Pokemonlist.create(:name => "マンタイン", :no => 226, :typea => "みず", :typeb => "ひこう")
Pokemonlist.create(:name => "エアームド", :no => 227, :typea => "はがね", :typeb => "ひこう")
Pokemonlist.create(:name => "デルビル", :no => 228, :typea => "ほのお", :typeb => "あく")
Pokemonlist.create(:name => "ヘルガー", :no => 229, :typea => "ほのお", :typeb => "あく")
Pokemonlist.create(:name => "キングドラ", :no => 230, :typea => "みず", :typeb => "ドラゴン")
Pokemonlist.create(:name => "ゴマゾウ", :no => 231, :typea => "じめん")
Pokemonlist.create(:name => "ドンファン", :no => 232, :typea => "じめん")
Pokemonlist.create(:name => "ポリゴン２", :no => 233, :typea => "ノーマル")
Pokemonlist.create(:name => "オドシシ", :no => 234, :typea => "ノーマル")
Pokemonlist.create(:name => "ドーブル", :no => 235, :typea => "ノーマル")
Pokemonlist.create(:name => "バルキー", :no => 236, :typea => "かくとう")
Pokemonlist.create(:name => "カポエラー", :no => 237, :typea => "かくとう")
Pokemonlist.create(:name => "ムチュール", :no => 238, :typea => "こおり", :typeb => "エスパー")
Pokemonlist.create(:name => "エレキッド", :no => 239, :typea => "でんき")
Pokemonlist.create(:name => "ブビィ", :no => 240, :typea => "ほのお")
Pokemonlist.create(:name => "ミルタンク", :no => 241, :typea => "ノーマル")
Pokemonlist.create(:name => "ハピナス", :no => 242, :typea => "ノーマル")
Pokemonlist.create(:name => "ライコウ", :no => 243, :typea => "でんき")
Pokemonlist.create(:name => "エンテイ", :no => 244, :typea => "ほのお")
Pokemonlist.create(:name => "スイクン", :no => 245, :typea => "みず")
Pokemonlist.create(:name => "ヨーギラス", :no => 246, :typea => "いわ", :typeb => "じめん")
Pokemonlist.create(:name => "サナギラス", :no => 247, :typea => "いわ", :typeb => "じめん")
Pokemonlist.create(:name => "バンギラス", :no => 248, :typea => "いわ", :typeb => "あく")
Pokemonlist.create(:name => "ルギア", :no => 249, :typea => "エスパー", :typeb => "ひこう")
Pokemonlist.create(:name => "ホウオウ", :no => 250, :typea => "ほのお", :typeb => "ひこう")
Pokemonlist.create(:name => "セレビィ", :no => 250, :typea => "エスパー")
Pokemonlist.create(:name => "キモリ", :no => 252, :typea => "くさ")
Pokemonlist.create(:name => "ジュプトル", :no => 253, :typea => "くさ")
Pokemonlist.create(:name => "ジュカイン", :no => 254, :typea => "くさ")
Pokemonlist.create(:name => "アチャモ", :no => 255, :typea => "ほのお", :typeb => "ひこう")
Pokemonlist.create(:name => "ワカシャモ", :no => 256, :typea => "ほのお", :typeb => "ひこう")
Pokemonlist.create(:name => "バシャーモ", :no => 257, :typea => "ほのお", :typeb => "かくとう")
Pokemonlist.create(:name => "ミズゴロウ", :no => 258, :typea => "みず")
Pokemonlist.create(:name => "ヌマクロー", :no => 259, :typea => "みず", :typeb => "じめん")
Pokemonlist.create(:name => "ラグラージ", :no => 260, :typea => "みず", :typeb => "じめん")